# Generated by Django 2.0.7 on 2018-08-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluser',
            name='paket_soal',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
