# Generated by Django 2.0.7 on 2018-10-20 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilUjian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai_mengerjakan', models.DateTimeField(auto_created=True)),
                ('selesai_mengerjakan', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='JawabanSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_jawaban', models.TextField()),
                ('huruf', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='JawabanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mengisi', models.DateTimeField(auto_now=True)),
                ('huruf_jawaban', models.CharField(max_length=1)),
                ('hasil_ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.HasilUjian')),
            ],
        ),
        migrations.CreateModel(
            name='SoalUjian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teks_soal', models.TextField()),
                ('huruf_jawaban', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('paket_soal', models.AutoField(primary_key=True, serialize=False)),
                ('nama_ujian', models.CharField(max_length=50)),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField()),
                ('waktu_diubah', models.DateTimeField(auto_now=True)),
                ('aktif', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='soalujian',
            name='ujian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.Ujian'),
        ),
        migrations.AddField(
            model_name='jawabanuser',
            name='soal_ujian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.SoalUjian'),
        ),
        migrations.AddField(
            model_name='jawabansoal',
            name='soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.SoalUjian'),
        ),
        migrations.AddField(
            model_name='hasilujian',
            name='ujian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.Ujian'),
        ),
        migrations.AddField(
            model_name='hasilujian',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
