# Generated by Django 2.0.7 on 2018-07-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_jawaban', models.CharField(max_length=255)),
                ('huruf_jawaban', models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='soalujian',
            old_name='jawaban',
            new_name='huruf_jawaban',
        ),
        migrations.AddField(
            model_name='jawaban',
            name='soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.SoalUjian'),
        ),
    ]
