# Generated by Django 2.0.7 on 2018-07-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0002_auto_20180729_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jawaban',
            new_name='JawabanSoal',
        ),
    ]
