# Generated by Django 2.0.7 on 2018-07-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0003_auto_20180729_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ujian',
            old_name='waktu_ditambahkan',
            new_name='waktu_diubah',
        ),
    ]
