# Generated by Django 2.0.7 on 2018-07-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0004_auto_20180729_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
