# Generated by Django 2.0.7 on 2018-07-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0005_ujian_aktif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jawabansoal',
            old_name='huruf_jawaban',
            new_name='huruf',
        ),
    ]
