# Generated by Django 2.0.7 on 2018-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0007_hasilujian_jawabanuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilujian',
            name='waktu_mulai_mengerjakan',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='jawabanuser',
            name='waktu_mengisi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
