# Generated by Django 2.0.7 on 2018-08-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0008_auto_20180731_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='paket_soal',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
