# Generated by Django 2.0.7 on 2018-08-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0009_ujian_paket_soal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilujian',
            name='waktu_selesai_mengerjakan',
        ),
        migrations.AddField(
            model_name='hasilujian',
            name='selesai_mengerjakan',
            field=models.BooleanField(default=False),
        ),
    ]
