# Generated by Django 2.0.7 on 2018-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0010_auto_20180801_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujian',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
    ]
