# Generated by Django 2.0.7 on 2018-10-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HasilUjianPDFConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_kiri', models.ImageField(upload_to='pdf/logo')),
                ('logo_kanan', models.ImageField(upload_to='pdf/logo')),
                ('teks_kop', models.CharField(max_length=255)),
                ('judul', models.CharField(max_length=255)),
                ('waktu_diubah', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
