# Generated by Django 2.0.7 on 2018-07-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilujianpdfconfig',
            name='logo_kanan',
            field=models.ImageField(upload_to='pdf/logo'),
        ),
        migrations.AlterField(
            model_name='hasilujianpdfconfig',
            name='logo_kiri',
            field=models.ImageField(upload_to='pdf/logo'),
        ),
    ]
