# Generated by Django 2.0.7 on 2018-07-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_auto_20180729_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilujianpdfconfig',
            name='waktu_diubah',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
